### ISSUE TITLE
equal_to should allow partially equal with different types

### ISSUE THREAD

**Issue by dten** [Valloric/hamcrest2-rust#1]
`PartialEq` has an `Rhs` associated type and can allow things to be different types. I have a type `A` that implements `PartialEq<B>` but equal_to requires the same type as far as I can tell.

this compiles and passes:
```
assert_that!(b == &[0.0, 1.0], is(true));
```

this does not compile:
```
assert_that!(b, is(equal_to(&[0.0, 1.0])));
```

**Comment by Valloric** [comment]
I'd be lying to you if I told you I knew how to fix this... :)

PR's are of course welcome.

**Comment by Valloric** [comment]
If you want to take a stab at it, [here's the implementation of equal_to](https://github.com/Valloric/hamcrest2-rust/blob/master/src/matchers/equal_to.rs) and [here are the tests for it](https://github.com/Valloric/hamcrest2-rust/blob/master/tests/equal_to.rs).

**Comment by Valloric** [comment]
For the record, @jwilm figured out the fix, I was completely clueless. :D

**Comment by Valloric** [comment]
Also released 0.2.3 with the fix. 

Thanks for the bug report!

**Comment by Valloric** [comment]
BTW, you can rewrite this:
```rust
assert_that!(b, is(equal_to(&[0.0, 1.0])));
```
to this:
```rust
assert_that!(b, eq(&[0.0, 1.0]));
```
Up to you of course.

**Comment by dten** [comment]
Awesome thanks both
