### ISSUE TITLE
Idiomatic macro usage in 2018 edition requires `#[allow(deprecated)]`

### ISSUE THREAD

**Issue by eliaslevy** [Valloric/hamcrest2-rust#10]
In 2018 Edition, importing the `assert_that!` macro via `use hamcrest2::assert_that;`, rather than using `#[cfg(test)] #[macro_use] extern crate hamcrest2;` at the crate root, the former of which is now idiomatic, requires using `#[allow(deprecated)]`, because `hamcrest2` root bring into scope and republishes the deprecated `core::assert_that` via `use hamcrest2::prelude::*;`.

It would be best if `hamcrest2::prelude` did not include the `pub use core::assert_that;` line to avoid this name clash.

**Comment by Valloric** [comment]
Apologies for the delay! 

Just released 0.3.0 that fixes this. Thanks for the heads-up!
