### ISSUE TITLE
Rename matcher Contains

### ISSUE THREAD

**Issue by povilasb** [Valloric/hamcrest2-rust#3]
I'd like to bring the original issue again: https://github.com/ujh/hamcrest-rust/issues/45
I made a PR for it: https://github.com/ujh/hamcrest-rust/pull/50
Would you be interested in merging? :)

**Comment by Valloric** [comment]
Thanks for interest in contributing! :)

This seems like it might not be worth breaking backwards compatibility for. I have a rather draconian view against API breakage which is basically never, ever break it unless absolutely necessary. This doesn't seem to pass that bar for me, sorry.

Ideally we'd be able to find a way that `contains` can take both a single item and a vector for multiple items. This might be doable (not sure) by making the param take a special type that can be auto-converted from both a vec of Ts and a single T. @jwilm You know rust better than I do; is this doable?

**Comment by jwilm** [comment]
Something [like this](https://play.rust-lang.org/?gist=2d5ee69d15b0edac07647138e281d233&version=stable&mode=debug&edition=2015) _might_ work depending on how the `contains` API is used in practice. There is a type inference issue that you can see by removing the hint in `main`. If it doesn't break the test suite, then maybe it's fine?

**Comment by Valloric** [comment]
@jwilm I like this! I'd go with "if it doesn't break the test suite, it should be good." 

@povilasb If you sent a PR with the implementation that @jwilm provided a prototype of, that would have a high chance of being merged.

**Comment by povilasb** [comment]
Okey, I might make some spare time this week ;)
